FROM rust:alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src       ./src
COPY resources ./resources
RUN cargo build --release

FROM alpine:latest
RUN apk add --no-cache wget
COPY --from=builder /app/target/release/rinha /rinha
EXPOSE 8080
ENTRYPOINT ["/rinha"]
